version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /data/test.txt:/app/data/test.txt # Bind mount for a single file
      - /keys:/app
    environment:
      - NODE_ENV=production
